// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdcnN8jG8SGTf7Eg9NAOpuUjbvujFPZDk',
    appId: '1:316793447034:web:f0853ccdffbbaa067751c3',
    messagingSenderId: '316793447034',
    projectId: 'karirku-final',
    authDomain: 'karirku-final.firebaseapp.com',
    storageBucket: 'karirku-final.firebasestorage.app',
    measurementId: 'G-TGXBBKT3FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmaK82x_m9a7l7CRquXHp3jx84KZgvRck',
    appId: '1:316793447034:android:34e9187770acc2977751c3',
    messagingSenderId: '316793447034',
    projectId: 'karirku-final',
    storageBucket: 'karirku-final.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBso4iiMK_woIdb3J9XV7CNYHWOV9egeXU',
    appId: '1:316793447034:ios:bdfda35c389803157751c3',
    messagingSenderId: '316793447034',
    projectId: 'karirku-final',
    storageBucket: 'karirku-final.firebasestorage.app',
    iosBundleId: 'com.example.karirkuApplication',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBso4iiMK_woIdb3J9XV7CNYHWOV9egeXU',
    appId: '1:316793447034:ios:bdfda35c389803157751c3',
    messagingSenderId: '316793447034',
    projectId: 'karirku-final',
    storageBucket: 'karirku-final.firebasestorage.app',
    iosBundleId: 'com.example.karirkuApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdcnN8jG8SGTf7Eg9NAOpuUjbvujFPZDk',
    appId: '1:316793447034:web:c32d0e1721b6c31b7751c3',
    messagingSenderId: '316793447034',
    projectId: 'karirku-final',
    authDomain: 'karirku-final.firebaseapp.com',
    storageBucket: 'karirku-final.firebasestorage.app',
    measurementId: 'G-KR853XQ4TQ',
  );
}
